# 安裝／移除 LobsterPulse watchdog 的登入啟動鏈（不需提權）。
#
#   pwsh -NoProfile -File runtime\install-watchdog.ps1            # 安裝／更新
#   pwsh -NoProfile -File runtime\install-watchdog.ps1 -Uninstall # 移除
#
# 為什麼繞這麼一圈：
# - 排程工作最乾淨，但 Register-ScheduledTask 在這台機器需要提權（實測存取被拒）。
# - 退回這台機器的慣例（Startup 放 .vbs）時撞到硬規則：.vbs 必須純 ASCII
#   （WSH 以 ANSI/cp950 解析，UTF-8 中文位元組會毀掉行結構），但專案路徑含
#   中文「監控」，且 D: 沒開 8.3 短名可繞。
# - 解法：.vbs 只指向 ~/.lobsterpulse/ 底下一支 ASCII 路徑的轉接器 .ps1。
#   .ps1 由 pwsh 讀，UTF-8 中文路徑沒問題。轉接器只有一行——真正的邏輯留在
#   repo 的 watchdog.ps1，不做第二份副本（踩雷 §26：硬編碼副本會長成殭屍）。

param([switch]$Uninstall)

$ErrorActionPreference = "Stop"
$startup = Join-Path $env:APPDATA "Microsoft\Windows\Start Menu\Programs\Startup"
$vbs = Join-Path $startup "lobsterpulse-watchdog.vbs"
$shim = Join-Path $env:USERPROFILE ".lobsterpulse\watchdog-launcher.ps1"
$real = Join-Path $PSScriptRoot "watchdog.ps1"

if ($Uninstall) {
  Remove-Item $vbs, $shim -Force -ErrorAction SilentlyContinue
  Get-CimInstance Win32_Process -Filter "Name='pwsh.exe'" |
    Where-Object { $_.CommandLine -like "*watchdog*" } |
    ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }
  "已移除 watchdog（$vbs / $shim）並停掉執行中的實例"
  return
}

if (-not (Test-Path $real)) { throw "找不到 $real" }
New-Item -ItemType Directory -Path (Split-Path $shim) -Force | Out-Null

# 轉接器：唯一的任務是把中文路徑交給 pwsh（.vbs 自己碰不得中文）
Set-Content -Path $shim -Encoding utf8 -Value @(
  "# 由 runtime\install-watchdog.ps1 產生，勿手改——邏輯在下面這支裡。",
  "& `"$real`""
)

$pwshExe = (Get-Process -Id $PID).Path
# .vbs 必須純 ASCII：這裡只出現 ASCII 路徑（%USERPROFILE% 展開後亦然）
$vbsBody = @(
  "' lobsterpulse-watchdog.vbs - launch LobsterPulse watchdog (hidden) at logon.",
  "' Generated by runtime\install-watchdog.ps1 - do not edit by hand.",
  "' MUST stay pure ASCII: WSH parses this as ANSI/cp950; UTF-8 bytes corrupt line structure.",
  "' Hide via Run's 0 flag, NOT -WindowStyle Hidden (that self-respawns into two processes).",
  "Set sh = CreateObject(""WScript.Shell"")",
  # VBScript 內要放引號得寫兩個；PowerShell 雙引號字串裡每個 "" 又代表一個 "，
  # 所以「VBS 的一個引號」= 這裡的 ""，「VBS 的兩個引號」= 這裡的 """"。
  "sh.Run """"""$pwshExe"""" -NoProfile -ExecutionPolicy Bypass -File """"$shim"""""", 0, False"
)
$nonAscii = $vbsBody | Where-Object { $_ -match "[^\x00-\x7F]" }
if ($nonAscii) { throw "產生的 .vbs 含非 ASCII 字元，中止：$nonAscii" }
Set-Content -Path $vbs -Value $vbsBody -Encoding ascii

"已安裝："
"  $vbs"
"  $shim  ->  $real"
